### ISSUE TITLE
(J) Multiple whole-genome alignment (slow, needs A from both groups, I)

### ISSUE THREAD

**Issue by LejlaMetohajrova** [fmfi-genomika/genomikaMalSym#11]
- The goal of this track is to create a whole-genome multiple alignment of several genomes
- Use genomes from part I as well as malGlo and malSym genomes from the browser
- Beware that malSym1 and malGlo1 should be correctly named, both the genome as a whole and their chromosomes as in the browser
- The task requires some preprocessing - renaming things etc (fast), alignment computation (slow, we recommend running on compbio servers) and postprocessing (fast/medium)
Preprocessing and possibly also part of running alignment can be reused between groups - collaborate
The notes from the last year consist of three parts: general introduction, Brona's notes (Example of use of tba in a different project), and student notes (Example of use of tba in a our project, display alignments).
Probably follow student notes.
The notes are not finished (end with "track does not work"), but the track was finished, see track "S. Align (L)" in sacCer3 browser. See final version of sacCer3 trackDb.ra on genomika server.
To run alignment, you need phylogenetic tree of these species. Use the tree from paper by Wu et al 2015 [4] - our species are in group B. Write the tree in the parenthesis notation
https://github.com/fmfi-genomika/genomika-2017/wiki/Alignments

**Comment by rasto2211** [comment]
The track seems to be working.

**Comment by rasto2211** [comment]
Docs done.

**Comment by rasto2211** [comment]
I regenerated the MAF file again and it seems to be alright now.
