### ISSUE TITLE
(L) Conserved elements by phastCons (medium, needs A,I,J)

### ISSUE THREAD

**Issue by LejlaMetohajrova** [fmfi-genomika/genomikaMalSym#16]
- Similar as track K, but uses a different program from the phast package. Phastcons is based on and HMM, finds contiguous conserved regions. The result is a list of conserved regions (bed format) as well as posterior probability of conserved region at each position (wig format)

- On sacCer3, wig format are e.g. tracks Cons. new (L), Cons. old (L); bed format track is PhastCons Most, but that was taken from the original UCSC database so no commands for it are available, but hopefully it should be easy to create and load.

https://github.com/fmfi-genomika/genomika-2017/wiki/Conservation

**Comment by rasto2211** [comment]
Added docs.
