### ISSUE TITLE
(A) Genome (fast)

### ISSUE THREAD

**Issue by Kalerab** [fmfi-genomika/genomikaMalSym#2]
Download genome in fasta format, add to browser
    Data malGlo [1], malSym [2]
    https://github.com/fmfi-genomika/genomika-2017/wiki/Setting-up-a-Yarrowia-lipolytica
    Important step not described is to rename chromosomes/contigs to something reasonable
    Genome versions are numbered, we will start with malGlo1 and malSym1
    Missing part in last-year documentation - adding species to hgcentral database
        look at existing records, e.g for yarLip1 to guess appropriate values
        taxonomy ID can be found at https://www.ncbi.nlm.nih.gov/taxonomy

hgsql hgcentral -e '
insert into dbDb values (...);

insert into defaultDb values (...);

insert into genomeClade values (...);

**Comment by rizip1** [comment]
@Kalerab @Simda93  what is the progress with this one?
I am currious about this line in task description
`Important step not described is to rename chromosomes/contigs to something reasonable`
I have seen that in the original file there are labels `something...chromosome: 1` ... `something...chromosome: 8` but in the `.fa` file that is updated in genomika server those lines are all missing.
I guess I depend on this one as in task B there is
`Coordinate with renaming chromosomes in step (1)`
written. But maybe I am wrong.
The file that I should use in issue 'B' contains `chromosome: 1` to `chromosome: 8` labels, so should not those labels be retained also in task 'A'?

**Comment by rizip1** [comment]
Seems that your format is fine, it was just my confusion sorry. Anyway how is this going? I cant see the genome in `http://genomika.compbio.fmph.uniba.sk/`. Do you plan to add it soon? I would need it to test addition of tracks in 'B' section.

**Comment by Simda93** [comment]
Genome can be found at genomika.compbio.fmph.uniba.sk/cgi-bin/hgTracks?db=malSym1 , 
it's not yet added to navigation menu.

**Comment by rasto2211** [comment]
Is this issue completely solved? Can we close it?

**Comment by LejlaMetohajrova** [comment]
Sorry. @Kalerab @Simda93 can we close it?

**Comment by Simda93** [comment]
except the wiki entry, task is done.

**Comment by Simda93** [comment]
wiki entry added
