### ISSUE TITLE
(E) Augustus (slow, needs A)

### ISSUE THREAD

**Issue by JakubNvk** [fmfi-genomika/genomikaMalSym#3]
* Run gene finder Augustus, create track with predicted genes (for comparison with annotation)
* Download and install software from http://bioinf.uni-greifswald.de/augustus/ (Already installed on compbio servers)
* Example of command line: augustus --uniqueGeneId=true --species=ustilago_maydis genome.fa > augustus.gtf
ustilago_maydis is a related fungal species used for training parameters
* The result needs to be converted from gtf to genepred, by gtfToGenePred (at genomika server) with option -genePredExt
* If you name your track augustus, genome browser will recognize it automatically, no need to modify trackDb.ra

**Comment by rasto2211** [comment]
Used ustilago_maydis model (fungi) since there's no MalSym model. From augustus docs:
```
Note that for closely related species usually only one version is necessary. For example, the human version is good for all mammals.
```

**Comment by rasto2211** [comment]
Output from gtfToGenePred
```
augustus.gtf doesn't appear to be a GTF file (GFF not supported by this program)
```

**Comment by rasto2211** [comment]
It seems that we need to remove lines which have transcript and gene in the third column.
```
cat augustus.gtf | grep -v "^#" | grep -Pv "\t(gene|transcript)\t" > augustus2.gtf
```
Transcript and gene lines have data in the 9th column in a format which does not agree with GTF spec.

**Comment by rasto2211** [comment]
Convert GTF to GenePredExt:
```
gtfToGenePred -genePredExt augustus2.gtf augustus.genePredExt
```

Load data from GenePredExt file to augustus SQL table:
```
hgLoadGenePred -genePredExt malSym1 augustus augustus.genePredExt
```

**Comment by rasto2211** [comment]
No need to modify `/kentsrc/trackDb/malSym/malSym1/trackDb.ra` since augustus track is already defined in `/kentsrc/trackDb/trackDb.ra`.

**Comment by rizip1** [comment]
@rasto2211 I suppose that it would be better to write those approaches to wiki rather than store them here.

**Comment by rasto2211** [comment]
I looked at augustus track in genome browser and it seems quite reasonable.

I also added [docs](https://github.com/fmfi-genomika/genomikaMalSym/wiki/(E)-Augustus-gene-predictions) to github wiki.
