### ISSUE TITLE
(D) tRNAscan-SE (medium, needs A)

### ISSUE THREAD

**Issue by LejlaMetohajrova** [fmfi-genomika/genomikaMalSym#4]
Run software for finding tRNA genes (for comparison with annotation)

- Download software from http://lowelab.ucsc.edu/tRNAscan-SE/ (already installed on compbio servers as tRNAscan-SE command)
- Convert output by script rna/tRNAscan-SEtoBED.py on github
- trackDb.ra record:

```
track tRNAs
shortLabel tRNA Genes
longLabel Transfer RNA Genes Identified with tRNAscan-SE
group genes
visibility hide
color 0,20,150
type bed 12
nextItemButton on
priority 10
```

**Comment by svklum** [comment]
This should be finished. The track should be visible on genomika.compbio.fmph.uniba.sk `tRNA Genes`. @Simda93 Can you please varify that this is correct and perhaps close this issue.

**Comment by rizip1** [comment]
Please add Wiki and close. Thanks

**Comment by svklum** [comment]
Wiki is already created and the issue should be finished.
I'm closing it.
