### ISSUE TITLE
(C) RepeatMasker (slow, needs A)

### ISSUE THREAD

**Issue by JakubNvk** [fmfi-genomika/genomikaMalSym#5]
* Run RepeatMasker program to find repeated sequences (use fungi as species)
* https://github.com/fmfi-genomika/genomika-2017/wiki/RepeatMasker
* RepeatMasker and repeat library installed at compbio and genomika servers, or request a copy for your computer, registration may take several days

**Comment by JakubNvk** [comment]
Registration successfully completed.

**Comment by JakubNvk** [comment]
Its pretty much done - I just need to upload it.

**Comment by rizip1** [comment]
Please add Wiki and close. Thanks

**Comment by JakubNvk** [comment]
- Track is loaded in the browser.
- Wiki page is created.
