### ISSUE TITLE
(I) Genomes for comparative genomics (fast, only one group)

### ISSUE THREAD

**Issue by rasto2211** [fmfi-genomika/genomikaMalSym#9]
* Download genomes of additional Malassezia species (other than malGlo and malSym)
Use list [here](https://www.ncbi.nlm.nih.gov/genome/?term=txid55193%5BOrganism%3Aexp%5D), download M. pachydermatis, M. nana, M. equina, M. caprae, M. dermatis, M. restricta
* Download one representative assembly per species (some species have multipe strains /assemblies)
* Rename chromosomes similarly as in A, name fasta files in a systematic way (malPac1.fa etc.)
* Store files in a directory at genomika server
* Do not forget to note down in your documentation the URL of each downloaded fasta file.

**Comment by JakubNvk** [comment]
The other group has already done this.
